services:
  app:
    container_name: nestjs_app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: "app"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "app", "-U", "app" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
    driver: local